CREATE USER HR_APP IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO HR_APP;
GRANT UNLIMITED TABLESPACE TO HR_APP;
GRANT CREATE ROLE TO HR_APP;

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE ROLE_EMPLOYEE';
    EXECUTE IMMEDIATE 'CREATE ROLE ROLE_MANAGER';
    EXECUTE IMMEDIATE 'CREATE ROLE ROLE_ACCOUNTANT';
    EXECUTE IMMEDIATE 'CREATE ROLE ROLE_HR';
EXCEPTION 
    WHEN OTHERS THEN 
        NULL; 
END;
/

DECLARE
    v_sql VARCHAR2(1000);
BEGIN
    FOR r IN (SELECT ORACLEUSER, POSITION, DEPARTMENTID FROM HR_APP.EMPLOYEE) LOOP

        BEGIN
            v_sql := 'CREATE USER ' || r.ORACLEUSER || ' IDENTIFIED BY 123';
            EXECUTE IMMEDIATE v_sql;

            v_sql := 'GRANT CREATE SESSION TO ' || r.ORACLEUSER;
            EXECUTE IMMEDIATE v_sql;
        EXCEPTION
            WHEN OTHERS THEN 
                NULL; 
        END;

        IF r.POSITION = 'MANAGER' THEN
            v_sql := 'GRANT ROLE_MANAGER TO ' || r.ORACLEUSER;
        ELSIF r.DEPARTMENTID = 2 THEN 
            v_sql := 'GRANT ROLE_HR TO ' || r.ORACLEUSER;
        ELSIF r.DEPARTMENTID = 3 THEN 
            v_sql := 'GRANT ROLE_ACCOUNTANT TO ' || r.ORACLEUSER;
        ELSE 
            v_sql := 'GRANT ROLE_EMPLOYEE TO ' || r.ORACLEUSER;
        END IF;
        
        EXECUTE IMMEDIATE v_sql;
    END LOOP;
END;
/


GRANT SELECT ON HR_APP.EMPLOYEE TO ROLE_EMPLOYEE;

GRANT SELECT ON HR_APP.EMPLOYEE TO ROLE_ACCOUNTANT;

GRANT SELECT, INSERT, UPDATE, DELETE ON HR_APP.EMPLOYEE TO ROLE_HR;

GRANT SELECT, INSERT, UPDATE, DELETE ON HR_APP.EMPLOYEE TO ROLE_MANAGER;


COMMIT;